/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EitherRouteImport } from './routes/_either'
import { Route as AuthorizedRouteImport } from './routes/_authorized'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthorizedIndexRouteImport } from './routes/_authorized/index'
import { Route as UploadedFilesSplatRouteImport } from './routes/uploaded-files/$'
import { Route as EitherCreateWorkspaceRouteImport } from './routes/_either/create-workspace'
import { Route as AuthorizedWorkspaceRouteImport } from './routes/_authorized/$workspace'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as EitherInviteTokenRouteImport } from './routes/_either/invite/$token'
import { Route as AuthorizedWorkspaceSettingsRouteImport } from './routes/_authorized/$workspace/settings'
import { Route as AuthorizedWorkspaceMainRouteImport } from './routes/_authorized/$workspace/_main'
import { Route as AuthorizedWorkspaceSettingsIndexRouteImport } from './routes/_authorized/$workspace/settings/index'
import { Route as AuthorizedWorkspaceMainIndexRouteImport } from './routes/_authorized/$workspace/_main/index'
import { Route as AuthorizedWorkspaceSettingsWorkspaceRouteImport } from './routes/_authorized/$workspace/settings/workspace'
import { Route as AuthorizedWorkspaceSettingsProfileRouteImport } from './routes/_authorized/$workspace/settings/profile'
import { Route as AuthorizedWorkspaceSettingsGeneralRouteImport } from './routes/_authorized/$workspace/settings/general'
import { Route as AuthorizedWorkspaceSettingsTeamsIndexRouteImport } from './routes/_authorized/$workspace/settings/teams/index'
import { Route as AuthorizedWorkspaceSettingsTeamsCreateRouteImport } from './routes/_authorized/$workspace/settings/teams/create'
import { Route as AuthorizedWorkspaceSettingsTeamsKeyRouteImport } from './routes/_authorized/$workspace/settings/teams/$key'
import { Route as AuthorizedWorkspaceMainTeamTeamKeyRouteImport } from './routes/_authorized/$workspace/_main/team/$teamKey'
import { Route as AuthorizedWorkspaceMainIssueKeyRouteImport } from './routes/_authorized/$workspace/_main/issue/$key'
import { Route as AuthorizedWorkspaceMainTeamTeamKeyIssuesIndexRouteImport } from './routes/_authorized/$workspace/_main/team/$teamKey/issues/index'
import { Route as AuthorizedWorkspaceMainTeamTeamKeyIssuesBoardRouteImport } from './routes/_authorized/$workspace/_main/team/$teamKey/issues/board'
import { Route as AuthorizedWorkspaceMainTeamTeamKeyIssuesBacklogRouteImport } from './routes/_authorized/$workspace/_main/team/$teamKey/issues/backlog'

const EitherRoute = EitherRouteImport.update({
  id: '/_either',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRoute = AuthorizedRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedIndexRoute = AuthorizedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorizedRoute,
} as any)
const UploadedFilesSplatRoute = UploadedFilesSplatRouteImport.update({
  id: '/uploaded-files/$',
  path: '/uploaded-files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EitherCreateWorkspaceRoute = EitherCreateWorkspaceRouteImport.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => EitherRoute,
} as any)
const AuthorizedWorkspaceRoute = AuthorizedWorkspaceRouteImport.update({
  id: '/$workspace',
  path: '/$workspace',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const EitherInviteTokenRoute = EitherInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => EitherRoute,
} as any)
const AuthorizedWorkspaceSettingsRoute =
  AuthorizedWorkspaceSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthorizedWorkspaceRoute,
  } as any)
const AuthorizedWorkspaceMainRoute = AuthorizedWorkspaceMainRouteImport.update({
  id: '/_main',
  getParentRoute: () => AuthorizedWorkspaceRoute,
} as any)
const AuthorizedWorkspaceSettingsIndexRoute =
  AuthorizedWorkspaceSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthorizedWorkspaceSettingsRoute,
  } as any)
const AuthorizedWorkspaceMainIndexRoute =
  AuthorizedWorkspaceMainIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthorizedWorkspaceMainRoute,
  } as any)
const AuthorizedWorkspaceSettingsWorkspaceRoute =
  AuthorizedWorkspaceSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AuthorizedWorkspaceSettingsRoute,
  } as any)
const AuthorizedWorkspaceSettingsProfileRoute =
  AuthorizedWorkspaceSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthorizedWorkspaceSettingsRoute,
  } as any)
const AuthorizedWorkspaceSettingsGeneralRoute =
  AuthorizedWorkspaceSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthorizedWorkspaceSettingsRoute,
  } as any)
const AuthorizedWorkspaceSettingsTeamsIndexRoute =
  AuthorizedWorkspaceSettingsTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => AuthorizedWorkspaceSettingsRoute,
  } as any)
const AuthorizedWorkspaceSettingsTeamsCreateRoute =
  AuthorizedWorkspaceSettingsTeamsCreateRouteImport.update({
    id: '/teams/create',
    path: '/teams/create',
    getParentRoute: () => AuthorizedWorkspaceSettingsRoute,
  } as any)
const AuthorizedWorkspaceSettingsTeamsKeyRoute =
  AuthorizedWorkspaceSettingsTeamsKeyRouteImport.update({
    id: '/teams/$key',
    path: '/teams/$key',
    getParentRoute: () => AuthorizedWorkspaceSettingsRoute,
  } as any)
const AuthorizedWorkspaceMainTeamTeamKeyRoute =
  AuthorizedWorkspaceMainTeamTeamKeyRouteImport.update({
    id: '/team/$teamKey',
    path: '/team/$teamKey',
    getParentRoute: () => AuthorizedWorkspaceMainRoute,
  } as any)
const AuthorizedWorkspaceMainIssueKeyRoute =
  AuthorizedWorkspaceMainIssueKeyRouteImport.update({
    id: '/issue/$key',
    path: '/issue/$key',
    getParentRoute: () => AuthorizedWorkspaceMainRoute,
  } as any)
const AuthorizedWorkspaceMainTeamTeamKeyIssuesIndexRoute =
  AuthorizedWorkspaceMainTeamTeamKeyIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AuthorizedWorkspaceMainTeamTeamKeyRoute,
  } as any)
const AuthorizedWorkspaceMainTeamTeamKeyIssuesBoardRoute =
  AuthorizedWorkspaceMainTeamTeamKeyIssuesBoardRouteImport.update({
    id: '/issues/board',
    path: '/issues/board',
    getParentRoute: () => AuthorizedWorkspaceMainTeamTeamKeyRoute,
  } as any)
const AuthorizedWorkspaceMainTeamTeamKeyIssuesBacklogRoute =
  AuthorizedWorkspaceMainTeamTeamKeyIssuesBacklogRouteImport.update({
    id: '/issues/backlog',
    path: '/issues/backlog',
    getParentRoute: () => AuthorizedWorkspaceMainTeamTeamKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/$workspace': typeof AuthorizedWorkspaceMainRouteWithChildren
  '/create-workspace': typeof EitherCreateWorkspaceRoute
  '/uploaded-files/$': typeof UploadedFilesSplatRoute
  '/': typeof AuthorizedIndexRoute
  '/$workspace/settings': typeof AuthorizedWorkspaceSettingsRouteWithChildren
  '/invite/$token': typeof EitherInviteTokenRoute
  '/$workspace/settings/general': typeof AuthorizedWorkspaceSettingsGeneralRoute
  '/$workspace/settings/profile': typeof AuthorizedWorkspaceSettingsProfileRoute
  '/$workspace/settings/workspace': typeof AuthorizedWorkspaceSettingsWorkspaceRoute
  '/$workspace/': typeof AuthorizedWorkspaceMainIndexRoute
  '/$workspace/settings/': typeof AuthorizedWorkspaceSettingsIndexRoute
  '/$workspace/issue/$key': typeof AuthorizedWorkspaceMainIssueKeyRoute
  '/$workspace/team/$teamKey': typeof AuthorizedWorkspaceMainTeamTeamKeyRouteWithChildren
  '/$workspace/settings/teams/$key': typeof AuthorizedWorkspaceSettingsTeamsKeyRoute
  '/$workspace/settings/teams/create': typeof AuthorizedWorkspaceSettingsTeamsCreateRoute
  '/$workspace/settings/teams': typeof AuthorizedWorkspaceSettingsTeamsIndexRoute
  '/$workspace/team/$teamKey/issues/backlog': typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesBacklogRoute
  '/$workspace/team/$teamKey/issues/board': typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesBoardRoute
  '/$workspace/team/$teamKey/issues': typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/$workspace': typeof AuthorizedWorkspaceMainIndexRoute
  '/create-workspace': typeof EitherCreateWorkspaceRoute
  '/uploaded-files/$': typeof UploadedFilesSplatRoute
  '/': typeof AuthorizedIndexRoute
  '/invite/$token': typeof EitherInviteTokenRoute
  '/$workspace/settings/general': typeof AuthorizedWorkspaceSettingsGeneralRoute
  '/$workspace/settings/profile': typeof AuthorizedWorkspaceSettingsProfileRoute
  '/$workspace/settings/workspace': typeof AuthorizedWorkspaceSettingsWorkspaceRoute
  '/$workspace/settings': typeof AuthorizedWorkspaceSettingsIndexRoute
  '/$workspace/issue/$key': typeof AuthorizedWorkspaceMainIssueKeyRoute
  '/$workspace/team/$teamKey': typeof AuthorizedWorkspaceMainTeamTeamKeyRouteWithChildren
  '/$workspace/settings/teams/$key': typeof AuthorizedWorkspaceSettingsTeamsKeyRoute
  '/$workspace/settings/teams/create': typeof AuthorizedWorkspaceSettingsTeamsCreateRoute
  '/$workspace/settings/teams': typeof AuthorizedWorkspaceSettingsTeamsIndexRoute
  '/$workspace/team/$teamKey/issues/backlog': typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesBacklogRoute
  '/$workspace/team/$teamKey/issues/board': typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesBoardRoute
  '/$workspace/team/$teamKey/issues': typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authorized': typeof AuthorizedRouteWithChildren
  '/_either': typeof EitherRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authorized/$workspace': typeof AuthorizedWorkspaceRouteWithChildren
  '/_either/create-workspace': typeof EitherCreateWorkspaceRoute
  '/uploaded-files/$': typeof UploadedFilesSplatRoute
  '/_authorized/': typeof AuthorizedIndexRoute
  '/_authorized/$workspace/_main': typeof AuthorizedWorkspaceMainRouteWithChildren
  '/_authorized/$workspace/settings': typeof AuthorizedWorkspaceSettingsRouteWithChildren
  '/_either/invite/$token': typeof EitherInviteTokenRoute
  '/_authorized/$workspace/settings/general': typeof AuthorizedWorkspaceSettingsGeneralRoute
  '/_authorized/$workspace/settings/profile': typeof AuthorizedWorkspaceSettingsProfileRoute
  '/_authorized/$workspace/settings/workspace': typeof AuthorizedWorkspaceSettingsWorkspaceRoute
  '/_authorized/$workspace/_main/': typeof AuthorizedWorkspaceMainIndexRoute
  '/_authorized/$workspace/settings/': typeof AuthorizedWorkspaceSettingsIndexRoute
  '/_authorized/$workspace/_main/issue/$key': typeof AuthorizedWorkspaceMainIssueKeyRoute
  '/_authorized/$workspace/_main/team/$teamKey': typeof AuthorizedWorkspaceMainTeamTeamKeyRouteWithChildren
  '/_authorized/$workspace/settings/teams/$key': typeof AuthorizedWorkspaceSettingsTeamsKeyRoute
  '/_authorized/$workspace/settings/teams/create': typeof AuthorizedWorkspaceSettingsTeamsCreateRoute
  '/_authorized/$workspace/settings/teams/': typeof AuthorizedWorkspaceSettingsTeamsIndexRoute
  '/_authorized/$workspace/_main/team/$teamKey/issues/backlog': typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesBacklogRoute
  '/_authorized/$workspace/_main/team/$teamKey/issues/board': typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesBoardRoute
  '/_authorized/$workspace/_main/team/$teamKey/issues/': typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signin'
    | '/signup'
    | '/$workspace'
    | '/create-workspace'
    | '/uploaded-files/$'
    | '/'
    | '/$workspace/settings'
    | '/invite/$token'
    | '/$workspace/settings/general'
    | '/$workspace/settings/profile'
    | '/$workspace/settings/workspace'
    | '/$workspace/'
    | '/$workspace/settings/'
    | '/$workspace/issue/$key'
    | '/$workspace/team/$teamKey'
    | '/$workspace/settings/teams/$key'
    | '/$workspace/settings/teams/create'
    | '/$workspace/settings/teams'
    | '/$workspace/team/$teamKey/issues/backlog'
    | '/$workspace/team/$teamKey/issues/board'
    | '/$workspace/team/$teamKey/issues'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/signup'
    | '/$workspace'
    | '/create-workspace'
    | '/uploaded-files/$'
    | '/'
    | '/invite/$token'
    | '/$workspace/settings/general'
    | '/$workspace/settings/profile'
    | '/$workspace/settings/workspace'
    | '/$workspace/settings'
    | '/$workspace/issue/$key'
    | '/$workspace/team/$teamKey'
    | '/$workspace/settings/teams/$key'
    | '/$workspace/settings/teams/create'
    | '/$workspace/settings/teams'
    | '/$workspace/team/$teamKey/issues/backlog'
    | '/$workspace/team/$teamKey/issues/board'
    | '/$workspace/team/$teamKey/issues'
  id:
    | '__root__'
    | '/_auth'
    | '/_authorized'
    | '/_either'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_authorized/$workspace'
    | '/_either/create-workspace'
    | '/uploaded-files/$'
    | '/_authorized/'
    | '/_authorized/$workspace/_main'
    | '/_authorized/$workspace/settings'
    | '/_either/invite/$token'
    | '/_authorized/$workspace/settings/general'
    | '/_authorized/$workspace/settings/profile'
    | '/_authorized/$workspace/settings/workspace'
    | '/_authorized/$workspace/_main/'
    | '/_authorized/$workspace/settings/'
    | '/_authorized/$workspace/_main/issue/$key'
    | '/_authorized/$workspace/_main/team/$teamKey'
    | '/_authorized/$workspace/settings/teams/$key'
    | '/_authorized/$workspace/settings/teams/create'
    | '/_authorized/$workspace/settings/teams/'
    | '/_authorized/$workspace/_main/team/$teamKey/issues/backlog'
    | '/_authorized/$workspace/_main/team/$teamKey/issues/board'
    | '/_authorized/$workspace/_main/team/$teamKey/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthorizedRoute: typeof AuthorizedRouteWithChildren
  EitherRoute: typeof EitherRouteWithChildren
  UploadedFilesSplatRoute: typeof UploadedFilesSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_either': {
      id: '/_either'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof EitherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized/': {
      id: '/_authorized/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthorizedIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/uploaded-files/$': {
      id: '/uploaded-files/$'
      path: '/uploaded-files/$'
      fullPath: '/uploaded-files/$'
      preLoaderRoute: typeof UploadedFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_either/create-workspace': {
      id: '/_either/create-workspace'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof EitherCreateWorkspaceRouteImport
      parentRoute: typeof EitherRoute
    }
    '/_authorized/$workspace': {
      id: '/_authorized/$workspace'
      path: '/$workspace'
      fullPath: '/$workspace'
      preLoaderRoute: typeof AuthorizedWorkspaceRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_either/invite/$token': {
      id: '/_either/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof EitherInviteTokenRouteImport
      parentRoute: typeof EitherRoute
    }
    '/_authorized/$workspace/settings': {
      id: '/_authorized/$workspace/settings'
      path: '/settings'
      fullPath: '/$workspace/settings'
      preLoaderRoute: typeof AuthorizedWorkspaceSettingsRouteImport
      parentRoute: typeof AuthorizedWorkspaceRoute
    }
    '/_authorized/$workspace/_main': {
      id: '/_authorized/$workspace/_main'
      path: ''
      fullPath: '/$workspace'
      preLoaderRoute: typeof AuthorizedWorkspaceMainRouteImport
      parentRoute: typeof AuthorizedWorkspaceRoute
    }
    '/_authorized/$workspace/settings/': {
      id: '/_authorized/$workspace/settings/'
      path: '/'
      fullPath: '/$workspace/settings/'
      preLoaderRoute: typeof AuthorizedWorkspaceSettingsIndexRouteImport
      parentRoute: typeof AuthorizedWorkspaceSettingsRoute
    }
    '/_authorized/$workspace/_main/': {
      id: '/_authorized/$workspace/_main/'
      path: '/'
      fullPath: '/$workspace/'
      preLoaderRoute: typeof AuthorizedWorkspaceMainIndexRouteImport
      parentRoute: typeof AuthorizedWorkspaceMainRoute
    }
    '/_authorized/$workspace/settings/workspace': {
      id: '/_authorized/$workspace/settings/workspace'
      path: '/workspace'
      fullPath: '/$workspace/settings/workspace'
      preLoaderRoute: typeof AuthorizedWorkspaceSettingsWorkspaceRouteImport
      parentRoute: typeof AuthorizedWorkspaceSettingsRoute
    }
    '/_authorized/$workspace/settings/profile': {
      id: '/_authorized/$workspace/settings/profile'
      path: '/profile'
      fullPath: '/$workspace/settings/profile'
      preLoaderRoute: typeof AuthorizedWorkspaceSettingsProfileRouteImport
      parentRoute: typeof AuthorizedWorkspaceSettingsRoute
    }
    '/_authorized/$workspace/settings/general': {
      id: '/_authorized/$workspace/settings/general'
      path: '/general'
      fullPath: '/$workspace/settings/general'
      preLoaderRoute: typeof AuthorizedWorkspaceSettingsGeneralRouteImport
      parentRoute: typeof AuthorizedWorkspaceSettingsRoute
    }
    '/_authorized/$workspace/settings/teams/': {
      id: '/_authorized/$workspace/settings/teams/'
      path: '/teams'
      fullPath: '/$workspace/settings/teams'
      preLoaderRoute: typeof AuthorizedWorkspaceSettingsTeamsIndexRouteImport
      parentRoute: typeof AuthorizedWorkspaceSettingsRoute
    }
    '/_authorized/$workspace/settings/teams/create': {
      id: '/_authorized/$workspace/settings/teams/create'
      path: '/teams/create'
      fullPath: '/$workspace/settings/teams/create'
      preLoaderRoute: typeof AuthorizedWorkspaceSettingsTeamsCreateRouteImport
      parentRoute: typeof AuthorizedWorkspaceSettingsRoute
    }
    '/_authorized/$workspace/settings/teams/$key': {
      id: '/_authorized/$workspace/settings/teams/$key'
      path: '/teams/$key'
      fullPath: '/$workspace/settings/teams/$key'
      preLoaderRoute: typeof AuthorizedWorkspaceSettingsTeamsKeyRouteImport
      parentRoute: typeof AuthorizedWorkspaceSettingsRoute
    }
    '/_authorized/$workspace/_main/team/$teamKey': {
      id: '/_authorized/$workspace/_main/team/$teamKey'
      path: '/team/$teamKey'
      fullPath: '/$workspace/team/$teamKey'
      preLoaderRoute: typeof AuthorizedWorkspaceMainTeamTeamKeyRouteImport
      parentRoute: typeof AuthorizedWorkspaceMainRoute
    }
    '/_authorized/$workspace/_main/issue/$key': {
      id: '/_authorized/$workspace/_main/issue/$key'
      path: '/issue/$key'
      fullPath: '/$workspace/issue/$key'
      preLoaderRoute: typeof AuthorizedWorkspaceMainIssueKeyRouteImport
      parentRoute: typeof AuthorizedWorkspaceMainRoute
    }
    '/_authorized/$workspace/_main/team/$teamKey/issues/': {
      id: '/_authorized/$workspace/_main/team/$teamKey/issues/'
      path: '/issues'
      fullPath: '/$workspace/team/$teamKey/issues'
      preLoaderRoute: typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesIndexRouteImport
      parentRoute: typeof AuthorizedWorkspaceMainTeamTeamKeyRoute
    }
    '/_authorized/$workspace/_main/team/$teamKey/issues/board': {
      id: '/_authorized/$workspace/_main/team/$teamKey/issues/board'
      path: '/issues/board'
      fullPath: '/$workspace/team/$teamKey/issues/board'
      preLoaderRoute: typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesBoardRouteImport
      parentRoute: typeof AuthorizedWorkspaceMainTeamTeamKeyRoute
    }
    '/_authorized/$workspace/_main/team/$teamKey/issues/backlog': {
      id: '/_authorized/$workspace/_main/team/$teamKey/issues/backlog'
      path: '/issues/backlog'
      fullPath: '/$workspace/team/$teamKey/issues/backlog'
      preLoaderRoute: typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesBacklogRouteImport
      parentRoute: typeof AuthorizedWorkspaceMainTeamTeamKeyRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthorizedWorkspaceMainTeamTeamKeyRouteChildren {
  AuthorizedWorkspaceMainTeamTeamKeyIssuesBacklogRoute: typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesBacklogRoute
  AuthorizedWorkspaceMainTeamTeamKeyIssuesBoardRoute: typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesBoardRoute
  AuthorizedWorkspaceMainTeamTeamKeyIssuesIndexRoute: typeof AuthorizedWorkspaceMainTeamTeamKeyIssuesIndexRoute
}

const AuthorizedWorkspaceMainTeamTeamKeyRouteChildren: AuthorizedWorkspaceMainTeamTeamKeyRouteChildren =
  {
    AuthorizedWorkspaceMainTeamTeamKeyIssuesBacklogRoute:
      AuthorizedWorkspaceMainTeamTeamKeyIssuesBacklogRoute,
    AuthorizedWorkspaceMainTeamTeamKeyIssuesBoardRoute:
      AuthorizedWorkspaceMainTeamTeamKeyIssuesBoardRoute,
    AuthorizedWorkspaceMainTeamTeamKeyIssuesIndexRoute:
      AuthorizedWorkspaceMainTeamTeamKeyIssuesIndexRoute,
  }

const AuthorizedWorkspaceMainTeamTeamKeyRouteWithChildren =
  AuthorizedWorkspaceMainTeamTeamKeyRoute._addFileChildren(
    AuthorizedWorkspaceMainTeamTeamKeyRouteChildren,
  )

interface AuthorizedWorkspaceMainRouteChildren {
  AuthorizedWorkspaceMainIndexRoute: typeof AuthorizedWorkspaceMainIndexRoute
  AuthorizedWorkspaceMainIssueKeyRoute: typeof AuthorizedWorkspaceMainIssueKeyRoute
  AuthorizedWorkspaceMainTeamTeamKeyRoute: typeof AuthorizedWorkspaceMainTeamTeamKeyRouteWithChildren
}

const AuthorizedWorkspaceMainRouteChildren: AuthorizedWorkspaceMainRouteChildren =
  {
    AuthorizedWorkspaceMainIndexRoute: AuthorizedWorkspaceMainIndexRoute,
    AuthorizedWorkspaceMainIssueKeyRoute: AuthorizedWorkspaceMainIssueKeyRoute,
    AuthorizedWorkspaceMainTeamTeamKeyRoute:
      AuthorizedWorkspaceMainTeamTeamKeyRouteWithChildren,
  }

const AuthorizedWorkspaceMainRouteWithChildren =
  AuthorizedWorkspaceMainRoute._addFileChildren(
    AuthorizedWorkspaceMainRouteChildren,
  )

interface AuthorizedWorkspaceSettingsRouteChildren {
  AuthorizedWorkspaceSettingsGeneralRoute: typeof AuthorizedWorkspaceSettingsGeneralRoute
  AuthorizedWorkspaceSettingsProfileRoute: typeof AuthorizedWorkspaceSettingsProfileRoute
  AuthorizedWorkspaceSettingsWorkspaceRoute: typeof AuthorizedWorkspaceSettingsWorkspaceRoute
  AuthorizedWorkspaceSettingsIndexRoute: typeof AuthorizedWorkspaceSettingsIndexRoute
  AuthorizedWorkspaceSettingsTeamsKeyRoute: typeof AuthorizedWorkspaceSettingsTeamsKeyRoute
  AuthorizedWorkspaceSettingsTeamsCreateRoute: typeof AuthorizedWorkspaceSettingsTeamsCreateRoute
  AuthorizedWorkspaceSettingsTeamsIndexRoute: typeof AuthorizedWorkspaceSettingsTeamsIndexRoute
}

const AuthorizedWorkspaceSettingsRouteChildren: AuthorizedWorkspaceSettingsRouteChildren =
  {
    AuthorizedWorkspaceSettingsGeneralRoute:
      AuthorizedWorkspaceSettingsGeneralRoute,
    AuthorizedWorkspaceSettingsProfileRoute:
      AuthorizedWorkspaceSettingsProfileRoute,
    AuthorizedWorkspaceSettingsWorkspaceRoute:
      AuthorizedWorkspaceSettingsWorkspaceRoute,
    AuthorizedWorkspaceSettingsIndexRoute:
      AuthorizedWorkspaceSettingsIndexRoute,
    AuthorizedWorkspaceSettingsTeamsKeyRoute:
      AuthorizedWorkspaceSettingsTeamsKeyRoute,
    AuthorizedWorkspaceSettingsTeamsCreateRoute:
      AuthorizedWorkspaceSettingsTeamsCreateRoute,
    AuthorizedWorkspaceSettingsTeamsIndexRoute:
      AuthorizedWorkspaceSettingsTeamsIndexRoute,
  }

const AuthorizedWorkspaceSettingsRouteWithChildren =
  AuthorizedWorkspaceSettingsRoute._addFileChildren(
    AuthorizedWorkspaceSettingsRouteChildren,
  )

interface AuthorizedWorkspaceRouteChildren {
  AuthorizedWorkspaceMainRoute: typeof AuthorizedWorkspaceMainRouteWithChildren
  AuthorizedWorkspaceSettingsRoute: typeof AuthorizedWorkspaceSettingsRouteWithChildren
}

const AuthorizedWorkspaceRouteChildren: AuthorizedWorkspaceRouteChildren = {
  AuthorizedWorkspaceMainRoute: AuthorizedWorkspaceMainRouteWithChildren,
  AuthorizedWorkspaceSettingsRoute:
    AuthorizedWorkspaceSettingsRouteWithChildren,
}

const AuthorizedWorkspaceRouteWithChildren =
  AuthorizedWorkspaceRoute._addFileChildren(AuthorizedWorkspaceRouteChildren)

interface AuthorizedRouteChildren {
  AuthorizedWorkspaceRoute: typeof AuthorizedWorkspaceRouteWithChildren
  AuthorizedIndexRoute: typeof AuthorizedIndexRoute
}

const AuthorizedRouteChildren: AuthorizedRouteChildren = {
  AuthorizedWorkspaceRoute: AuthorizedWorkspaceRouteWithChildren,
  AuthorizedIndexRoute: AuthorizedIndexRoute,
}

const AuthorizedRouteWithChildren = AuthorizedRoute._addFileChildren(
  AuthorizedRouteChildren,
)

interface EitherRouteChildren {
  EitherCreateWorkspaceRoute: typeof EitherCreateWorkspaceRoute
  EitherInviteTokenRoute: typeof EitherInviteTokenRoute
}

const EitherRouteChildren: EitherRouteChildren = {
  EitherCreateWorkspaceRoute: EitherCreateWorkspaceRoute,
  EitherInviteTokenRoute: EitherInviteTokenRoute,
}

const EitherRouteWithChildren =
  EitherRoute._addFileChildren(EitherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthorizedRoute: AuthorizedRouteWithChildren,
  EitherRoute: EitherRouteWithChildren,
  UploadedFilesSplatRoute: UploadedFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
